---
linters:
  disable:
    - contextcheck
    - depguard
    - dupl
    - exhaustruct
    - forbidigo
    - gci
    - gochecknoglobals
    - godox
    - goerr113
    - gomnd
    - lll
    - nlreturn
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
    - tagalign
    - intrange
    - copyloopvar
    - perfsprint
  enable-all: true
linters-settings:
  funlen:
    lines: 80
