repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: docs/swagger/swagger.json
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
      - id: golangci-lint
        args: [--timeout=10m]
        exclude: ^docs/
  - repo: https://gitlab.healthcareit.net/revex/common/tools/pre-commit-hooks/pre-commit-golang
    rev: v1.3.1
    hooks:
      - id: go-test
        exclude: ^docs/
